# Generated by Django 3.2 on 2022-06-28 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(blank=True, null=True, verbose_name='Метка')),
                ('balance', models.DecimalField(decimal_places=18, max_digits=32, verbose_name='Баланс')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.UUIDField(unique=True, verbose_name='Идентификатор транзакции')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=32, verbose_name='Сумма')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.wallet', verbose_name='Кошелек')),
            ],
        ),
    ]
